image: gitpod/workspace-dotnet
tasks:
  - init: dotnet restore
vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.8.1:Und1hQIrCL6QCVpIlT9ZRw==
    - ms-dotnettools.csharp@1.21.17:5/iI88WHX4j3iL5jASDTYQ==
